### ISSUE TITLE
error after install 

### ISSUE THREAD

**Issue by m49n** [RomainMazB/octobercms-frontend-model-editor#3] opened 2020-05-23 13:33 UTC
![image](https://user-images.githubusercontent.com/15114737/82732000-1b871b00-9d13-11ea-8217-c9e2fe77ef25.png)

**Comment by m49n** [comment] 2020-05-23 13:38
![image](https://user-images.githubusercontent.com/15114737/82732100-c8fa2e80-9d13-11ea-80cd-471f1a44bc45.png)

**Comment by RomainMazB** [comment] 2020-05-24 21:54
This is probably related to [the first one issue](https://github.com/RomainMazB/octobercms-frontend-model-editor/issues/2): the `CREATE TABLE` statement failed so for sure, the table doesn't exist.

Let me know if the uninstall/reinstall process fix the issue. If it doesn't, please provide more information about your database environment, especially the used version of MySQL.

**Comment by RomainMazB** [comment] 2020-06-12 10:20
Closing this as it seems like the problem is solved. Please comment if it's not.

**Closed as completed by RomainMazB** 2020-06-12 10:20 UTC
Labels: unconfirmed bug
